Sparsity update
ModelTC/llmc pull request #93
Opened 2024-09-14 06:38 UTC by guanchenl

I update some sparsity codes:

- semi-structured support
- OOM reduced

Best

2024-09-14 08:24 UTC, Harahan approved these changes

2024-09-15 12:29 UTC, Harahan commented
@guanchenl Could you use ``pre-commit`` to modify the format before pr?

2024-09-15 13:29 UTC, Harahan requested changes
modify format

2024-09-16 04:06 UTC, closed without merging

2024-09-16 04:10 UTC, guanchenl commented
i closed this pr for now, but i will resubmit it soon. i am considering the risk of submitting pr with a work devices.
________________________________
发件人: Harahan ***@***.***>
发送时间: 2024年9月15日 13:29
收件人: ModelTC/llmc ***@***.***>
抄送: guanchenl ***@***.***>; Mention ***@***.***>
主题: Re: [ModelTC/llmc] Sparsity update (PR #93)


@Harahan requested changes on this pull request.

modify format

―
Reply to this email directly, view it on GitHub<https://github.com/ModelTC/llmc/pull/93#pullrequestreview-2305361879>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BFAE2EFB5BIW3J5EK2RTWY3ZWWDVLAVCNFSM6AAAAABOGSLYPKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGMBVGM3DCOBXHE>.
You are receiving this because you were mentioned.Message ID: ***@***.***>